// <auto-generated />
using System;
using AgriActifs.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AgriActifs.Web.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260728023304_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("agriactifs")
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AgriActifs.Web.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.PermissionDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Action")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("PropertyName")
                        .HasColumnType("text");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Resource", "Action", "PropertyName");

                    b.ToTable("PermissionDefinitions", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.RolePermissionGrant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean");

                    b.Property<int>("PermissionDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDefinitionId");

                    b.HasIndex("RoleId", "PermissionDefinitionId")
                        .IsUnique();

                    b.ToTable("RolePermissionGrants", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.SecuredEndpoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("PermissionDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PermissionDefinitionId");

                    b.HasIndex("Area", "Controller", "Action", "HttpMethod")
                        .IsUnique();

                    b.ToTable("SecuredEndpoints", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.ActifAgricole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("AcquisitionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Brand")
                        .HasColumnType("text");

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<string>("InternalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LocationNote")
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int?>("ParcelleId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ResidualValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<int?>("UsefulLifeYears")
                        .HasColumnType("integer");

                    b.Property<int?>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.HasIndex("ExploitationId", "InternalCode")
                        .IsUnique();

                    b.ToTable("ActifsAgricoles", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Assolement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("ParcelleId")
                        .HasColumnType("integer");

                    b.Property<string>("Season")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("YieldPerHa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.ToTable("Assolements", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Exploitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ProductionType")
                        .HasColumnType("text");

                    b.Property<string>("Province")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAreaHa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Exploitations", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.ExploitationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExploitationId", "UserId")
                        .IsUnique();

                    b.ToTable("ExploitationUsers", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Fournisseur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExploitationId");

                    b.ToTable("Fournisseurs", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.InterventionMaintenance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActifAgricoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("LaborCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PartsCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("PlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Report")
                        .HasColumnType("text");

                    b.Property<int>("Statut")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActifAgricoleId");

                    b.HasIndex("ExploitationId");

                    b.ToTable("Interventions", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Parcelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AreaHa")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<bool>("HasIrrigation")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("SoilType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExploitationId", "Code")
                        .IsUnique();

                    b.ToTable("Parcelles", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.StockArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Categorie")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExploitationId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LotNumber")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantityOnHand")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<decimal>("ReorderLevel")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ExploitationId", "Sku")
                        .IsUnique();

                    b.ToTable("StockArticles", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.StockMouvement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedByUserId")
                        .HasColumnType("text");

                    b.Property<DateTime>("MovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<int>("StockArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StockArticleId");

                    b.ToTable("StockMouvements", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.ReportDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredPermissionCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("RequiredPermissionCode");

                    b.ToTable("ReportDefinitions", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveThemeId")
                        .HasColumnType("integer");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DefaultCulture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LockoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<int>("MaxFailedAccessAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("RequireConfirmedEmail")
                        .HasColumnType("boolean");

                    b.Property<bool>("RequireTwoFactor")
                        .HasColumnType("boolean");

                    b.Property<int>("SessionTimeoutMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("SmtpHost")
                        .HasColumnType("text");

                    b.Property<int>("SmtpPort")
                        .HasColumnType("integer");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("boolean");

                    b.Property<string>("SmtpUser")
                        .HasColumnType("text");

                    b.Property<string>("Tagline")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ActiveThemeId");

                    b.ToTable("SystemSettings", "agriactifs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ActiveThemeId = 1,
                            AppName = "GISEBS Secure MVC Starter",
                            DefaultCulture = "fr-FR",
                            LockoutMinutes = 15,
                            MaxFailedAccessAttempts = 5,
                            RequireConfirmedEmail = true,
                            RequireTwoFactor = false,
                            SessionTimeoutMinutes = 30,
                            SmtpPort = 587,
                            SmtpUseSsl = true,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AgriActifs.Web.Models.ThemeDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CssVariables")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ThemeDefinitions", "agriactifs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "default",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssVariables = "{\r\n  \"--gise-primary\": \"#1e40af\",\r\n  \"--gise-primary-dark\": \"#1e3a8a\",\r\n  \"--gise-accent\": \"#0ea5e9\",\r\n  \"--gise-accent-soft\": \"#e0f2fe\",\r\n  \"--gise-success\": \"#059669\",\r\n  \"--gise-warning\": \"#d97706\",\r\n  \"--gise-danger\": \"#dc2626\",\r\n  \"--gise-sidebar\": \"#0f172a\",\r\n  \"--gise-sidebar-hover\": \"#1e293b\",\r\n  \"--gise-sidebar-active\": \"#2563eb\",\r\n  \"--gise-surface\": \"#ffffff\",\r\n  \"--gise-bg\": \"#f1f5f9\",\r\n  \"--gise-border\": \"#e2e8f0\",\r\n  \"--gise-text\": \"#0f172a\",\r\n  \"--gise-text-muted\": \"#64748b\"\r\n}",
                            Description = "Palette bleue d'origine",
                            IsActive = true,
                            IsSystem = true,
                            Name = "GISEBS Default"
                        },
                        new
                        {
                            Id = 2,
                            Code = "corporate",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssVariables = "{\r\n  \"--gise-primary\": \"#374151\",\r\n  \"--gise-primary-dark\": \"#1f2937\",\r\n  \"--gise-accent\": \"#6b7280\",\r\n  \"--gise-accent-soft\": \"#f3f4f6\",\r\n  \"--gise-success\": \"#059669\",\r\n  \"--gise-warning\": \"#d97706\",\r\n  \"--gise-danger\": \"#dc2626\",\r\n  \"--gise-sidebar\": \"#111827\",\r\n  \"--gise-sidebar-hover\": \"#1f2937\",\r\n  \"--gise-sidebar-active\": \"#4b5563\",\r\n  \"--gise-surface\": \"#ffffff\",\r\n  \"--gise-bg\": \"#f9fafb\",\r\n  \"--gise-border\": \"#e5e7eb\",\r\n  \"--gise-text\": \"#111827\",\r\n  \"--gise-text-muted\": \"#6b7280\"\r\n}",
                            Description = "Tons neutres professionnels",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Corporate"
                        },
                        new
                        {
                            Id = 3,
                            Code = "ocean",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CssVariables = "{\r\n  \"--gise-primary\": \"#0d9488\",\r\n  \"--gise-primary-dark\": \"#0f766e\",\r\n  \"--gise-accent\": \"#06b6d4\",\r\n  \"--gise-accent-soft\": \"#cffafe\",\r\n  \"--gise-success\": \"#059669\",\r\n  \"--gise-warning\": \"#d97706\",\r\n  \"--gise-danger\": \"#dc2626\",\r\n  \"--gise-sidebar\": \"#134e4a\",\r\n  \"--gise-sidebar-hover\": \"#115e59\",\r\n  \"--gise-sidebar-active\": \"#0d9488\",\r\n  \"--gise-surface\": \"#ffffff\",\r\n  \"--gise-bg\": \"#f0fdfa\",\r\n  \"--gise-border\": \"#ccfbf1\",\r\n  \"--gise-text\": \"#134e4a\",\r\n  \"--gise-text-muted\": \"#5eead4\"\r\n}",
                            Description = "Bleu-vert moderne",
                            IsActive = true,
                            IsSystem = true,
                            Name = "Ocean"
                        });
                });

            modelBuilder.Entity("AgriActifs.Web.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<bool>("EmailNotifications")
                        .HasColumnType("boolean");

                    b.Property<string>("JobTitle")
                        .HasColumnType("text");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles", "agriactifs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", "agriactifs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", "agriactifs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", "agriactifs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", "agriactifs");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", "agriactifs");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.RolePermissionGrant", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Authorization.PermissionDefinition", "Permission")
                        .WithMany("RoleGrants")
                        .HasForeignKey("PermissionDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.SecuredEndpoint", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Authorization.PermissionDefinition", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionDefinitionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.ActifAgricole", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Actifs")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriActifs.Web.Models.Ferme.Parcelle", "Parcelle")
                        .WithMany()
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Exploitation");

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Assolement", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Parcelle", "Parcelle")
                        .WithMany("Assolements")
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parcelle");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.ExploitationUser", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Members")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exploitation");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Fournisseur", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Fournisseurs")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exploitation");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.InterventionMaintenance", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.ActifAgricole", "Actif")
                        .WithMany("Interventions")
                        .HasForeignKey("ActifAgricoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Interventions")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actif");

                    b.Navigation("Exploitation");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Parcelle", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Parcelles")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exploitation");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.StockArticle", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.Exploitation", "Exploitation")
                        .WithMany("Stocks")
                        .HasForeignKey("ExploitationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exploitation");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.StockMouvement", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Ferme.StockArticle", "StockArticle")
                        .WithMany("Mouvements")
                        .HasForeignKey("StockArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockArticle");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.ReportDefinition", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Authorization.PermissionDefinition", "RequiredPermission")
                        .WithMany()
                        .HasForeignKey("RequiredPermissionCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequiredPermission");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.SystemSettings", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.ThemeDefinition", null)
                        .WithMany()
                        .HasForeignKey("ActiveThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriActifs.Web.Models.UserProfile", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("AgriActifs.Web.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AgriActifs.Web.Models.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Authorization.PermissionDefinition", b =>
                {
                    b.Navigation("RoleGrants");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.ActifAgricole", b =>
                {
                    b.Navigation("Interventions");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Exploitation", b =>
                {
                    b.Navigation("Actifs");

                    b.Navigation("Fournisseurs");

                    b.Navigation("Interventions");

                    b.Navigation("Members");

                    b.Navigation("Parcelles");

                    b.Navigation("Stocks");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.Parcelle", b =>
                {
                    b.Navigation("Assolements");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Ferme.StockArticle", b =>
                {
                    b.Navigation("Mouvements");
                });

            modelBuilder.Entity("AgriActifs.Web.Models.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
